
# Track that we've found a chunk and are attempting to kill trees in it.
scoreboard players set $scoreboardcat ctk.Stage 1

# Pick the appropriate kill algorithm based on our configuration.
# For most scenarios, 4x4 seems to be the best balance of CPU usage and speed.
#
# Like our checks folder, this code is not generated by hand, but is instead generated using
# a node JavaScript file found at data/caerucat-treeless/functions/treekiller/checks/kills.js
execute if score $scoreboardcat ctk.Strength matches 1 run function caerucat-treeless:treekiller/kills/kill2x2
execute if score $scoreboardcat ctk.Strength matches 2 run function caerucat-treeless:treekiller/kills/kill4x4
execute if score $scoreboardcat ctk.Strength matches 3 run function caerucat-treeless:treekiller/kills/kill8x8
